### ISSUE TITLE
Errors and "squished" image when running example

### ISSUE THREAD

**Issue by leouieda** [ucgmsim/GMSimViz#24]
I tried running the first example in the README (`gmsimviz sample_data/fault.srf` from the root of the repository) and got the expected error messages but also some other ones complaining about files not found:

```
psxy: Error for input file: No such file (resources/Paths/lds-nz-coastlines-and-islands/150k.gmt)
grdimage: Error: (x_max-x_min) must equal (NX + eps) * x_inc), where NX is an integer and |eps| <= 0.0001.
grdimage (gmtlib_read_grd_info): Use grdedit -A on your grid file to make region and increments compatible [/home/leo/src/GMSimViz/resources/Topo/srtm_all_filt_nz_i5.grd]
grdimage: Error: (x_max-x_min) must equal (NX + eps) * x_inc), where NX is an integer and |eps| <= 0.0001.
grdimage (gmtlib_read_grd_info): Use grdedit -A on your grid file to make region and increments compatible [/home/leo/src/GMSimViz/resources/Topo/srtm_all_filt_nz.grd]
grdimage: File /home/leo/miniconda3/envs/GMSymVis/share/gmt/cpt/resources/cpt/palm_springs_nz_topo.cpt not found
[Session gmt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
psclip: Error for input file: No such file (resources/Paths/lds-nz-coastlines-and-islands/150k.gmt)
psxy: Error for input file: No such file (resources/Paths/lds-nz-lake-polygons/150k.gmt)
psxy: Error for input file: No such file (resources/Paths/lds-nz-river-polygons/150k.gmt)
psxy: Error for input file: No such file (resources/Paths/lds-nz-coastlines-and-islands/150k.gmt)
```

The files do exist in `resources`. But the I don't know why it's looking for the `palm_springs_nz_topo.cpt` file in my GMT install directory instead of the `resources` folder.

The resulting image is also distorted with a lot of empty transparent space (`fault_perspective.png`):

![fault_perspective](https://user-images.githubusercontent.com/290082/53979160-1c517400-40b1-11e9-942c-514d7de7b5c3.png)

openjournals/joss-reviews#808

**Comment by viktor76525** [comment]
Did you get any error when running setup.py `python setup.py install --user` or similar?
The reason is the missing paths are relative when they have to be absolute.
"resources" gets changed to the absolute path (in gmsimviz/config.json) at the start of setup.py. the original is just to make tests work before the gmsimviz package is installed

`/home/vap30/.local/lib64/python3.6/site-packages/GMSimViz-1.2.1-py3.6.egg/gmsimviz/config.json`
where your path will be slightly different should contain an absolute path:
```
{
"GMT_DATA" : "/home/vap30/ucgmsim/GMSimViz/resources"
}
```

I am not sure about the squashed image but it could be a side effect of other errors.

**Comment by leouieda** [comment]
OK, I managed to track it down. I had installed the project with `pip install .` to test it and forgot to revert back to `setup.py install`. Doing the `python setup.py install` got the example to run correctly. So something in your `setup.py` makes it incompatible with pip, which might be worth fixing since pip is the defacto way of installing Python software.

**Comment by leouieda** [comment]
To be clear, I don't think making it compatible with pip is a requirement for the JOSS publication. It's just a recommendation that will make GMSimViz easier to use. The instructions on the README work, they're just not following the Python community standards.

**Comment by viktor76525** [comment]
I wasn't aware of using pip to install packages in that way.
This is getting tricky. I can override the install function to add the absolute path first but pip will first copy setup.py to a temporary location so the path is wrong (can't use __file__ to find repo root). Ideally resources shouldn't be part of the package data because of their size and being less-related to code, updates in one vs the other.
The other option is make the resource folder location a non-optional parameter to the install but I was trying to streamline the install process.

**Comment by leouieda** [comment]
The advantage of having it pip-compatible is that you could then publish to PyPI and allow people to `pip install gmsimviz`. But hosting a lot of data is a difficult thing. I hadn't considered that. How about having the resources be defined at run-time? 

If they're "not part of the package" then the user should be able to control where they are stored. That's how I handle sample data for my packages. I built a library called [pooch](https://github.com/fatiando/pooch) that takes care of downloading the data and saving it somewhere. It has built-in support for checking user defined environment variables.

**Comment by viktor76525** [comment]
I think this covers it (https://github.com/ucgmsim/GMSimViz/commit/6e831ce638dedb93fbeaf893d4f8d07a853e07fd)

**Comment by leouieda** [comment]
In this case, the `setup.py` is still trying to set the resources right?

**Comment by viktor76525** [comment]
only if run directly, not with pip. do you think it should be optional either way?

**Comment by leouieda** [comment]
No, that's fine since the user can control it at runtime with the environment variable. Nice!
